### ISSUE TITLE
Счетчик непрочитанных писем "на виду"

### ISSUE THREAD

**Issue by alexander-lysenko** [epifanovmd/Gmail-Notify#1]
Я предлагаю этой программе небольшое обновление, помогающее следить за количеством не прочитанных писем. Это необходимо, например, если отошел от компьютера, оповещение показалось и ушло, а ты приходишь такой, и не знаешь, что тебе писали;
ну и чтобы лишний раз не открывать браузер с почтой, для проверки.

Я добавил в контекстное меню еще один пункт, который чекает количество непрочитанных писем.
![2](https://cloud.githubusercontent.com/assets/16338936/18787109/0bd51578-81aa-11e6-9a21-a39a9607de6a.png) 
Эта же информация выводится и в подсказку на самой иконке.
![default](https://cloud.githubusercontent.com/assets/16338936/18787108/0bd229e4-81aa-11e6-843e-f6bb93324995.png)

И обновляется этот счетчик в то же время, в которое и происходит сама удаленная проверка писем программой.

Вот исправленный текст формы
[Form1.txt](https://github.com/bananowars/Gmail-Notify/files/489752/Form1.txt)

**Comment by bananowars** [comment]
Спасибо нормально сделал, я просто не хотел больше делать)
